#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/data/mnp34/bladder/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/data/mnp34/bladder/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/data/mnp34/scs_model-main/step_3/neuralnetwork/code/x86_64/.libs/libnrnmech.so" "$@"
